In [1]:
import sys
def custom_accuracy(y_test,y_pred,thresold):
    right = 0

    l = len(y_pred)
    for i in range(0,l):
        if(abs(y_pred[i]-y_test[i]) <= thresold):
            right += 1
    return ((right/l)*100)


import pandas as pd
# Importing the dataset
dataset = pd.read_csv('data\odi.csv')
X = dataset.iloc[:,[7,8,9,12,13]].values
y = dataset.iloc[:, 14].values

[[0.00e+00 0.00e+00 1.00e-01 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 2.00e-01 0.00e+00 0.00e+00]
 [4.00e+00 0.00e+00 3.00e-01 0.00e+00 0.00e+00]
 ...
 [2.01e+02 8.00e+00 4.94e+01 5.90e+01 1.80e+01]
 [2.02e+02 8.00e+00 4.95e+01 5.90e+01 1.80e+01]
 [2.03e+02 8.00e+00 4.96e+01 5.90e+01 1.80e+01]]
[301 301 301 ... 203 203 203]


In [2]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [3]:
X_train

array([[ 0.09370533,  0.44565669,  0.18010786,  0.84849475,  0.3048047 ],
       [ 0.01649844,  0.44565669, -0.2551692 , -0.89540433, -0.76114359],
       [ 1.97240628,  1.31445566,  1.61933043,  0.35023787, -0.56127828],
       ...,
       [ 0.55694666, -0.85754176,  0.03267531,  2.02295739,  2.56994483],
       [-0.53681759,  0.01125721, -0.47982834, -0.9309941 , -0.76114359],
       [-0.8971164 , -0.85754176, -0.90808481, -0.75304522, -0.02830414]])

In [4]:
y_train

array([252, 230, 295, ..., 401, 302, 247], dtype=int64)

In [5]:
from sklearn.linear_model import LinearRegression
lin = LinearRegression()
lin.fit(X_train,y_train)

# Testing the dataset on trained model
y_pred = lin.predict(X_test)

In [6]:
score = lin.score(X_test,y_test)*100

In [7]:
score

52.737657811129445

In [8]:
import numpy as np
new_prediction = lin.predict(sc.transform(np.array([[sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4],sys.argv[5]]])))
print("Prediction score:" , new_prediction)
print(new_prediction)
sys.stdout.flush()

Prediction score: [322.42983935]
